"use client"

import { useState, useMemo } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { DollarSign, TrendingUp, Users, Eye, BarChart3, Download } from "lucide-react"
import type { Invoice, Product } from "@/types/app"
import { formatCurrency, formatDate } from "@/lib/utils"
import { exportCustomerProfitToExcel } from "@/lib/excel-utils"

interface CustomerProfitDetailsProps {
  invoices: Invoice[]
  products: Product[]
  currentAppCurrency: string
  onViewInvoice: (invoice: Invoice) => void
}

export function CustomerProfitDetails({
  invoices,
  products,
  currentAppCurrency,
  onViewInvoice,
}: CustomerProfitDetailsProps) {
  const [selectedCustomer, setSelectedCustomer] = useState<string | null>(null)

  const customerNames = useMemo(() => {
    const names = new Set<string>()
    invoices.forEach((invoice) => names.add(invoice.customerName))
    return Array.from(names).sort()
  }, [invoices])

  const customerProfitData = useMemo(() => {
    if (!selectedCustomer) return null

    const customerInvoices = invoices.filter((inv) => inv.customerName === selectedCustomer)

    let totalCustomerSales = 0
    let totalCustomerCost = 0
    const productSales: {
      [productId: string]: {
        productName: string
        quantitySold: number
        totalSales: number
        totalCost: number
        profit: number
      }
    } = {}

    customerInvoices.forEach((invoice) => {
      totalCustomerSales += invoice.totalAmount
      totalCustomerCost += invoice.totalCost

      invoice.items.forEach((item) => {
        if (!productSales[item.productId]) {
          productSales[item.productId] = {
            productName: item.productName,
            quantitySold: 0,
            totalSales: 0,
            totalCost: 0,
            profit: 0,
          }
        }
        productSales[item.productId].quantitySold += item.quantity
        productSales[item.productId].totalSales += item.quantity * item.unitPrice
        productSales[item.productId].totalCost += item.quantity * item.costPrice
        productSales[item.productId].profit += item.quantity * (item.unitPrice - item.costPrice)
      })
    })

    const totalCustomerProfit = totalCustomerSales - totalCustomerCost
    const customerProfitPercentage = totalCustomerSales > 0 ? (totalCustomerProfit / totalCustomerSales) * 100 : 0

    return {
      totalCustomerSales,
      totalCustomerCost,
      totalCustomerProfit,
      customerProfitPercentage,
      productSales: Object.values(productSales),
      customerInvoices,
    }
  }, [selectedCustomer, invoices])

  const handleExportCustomerProfit = () => {
    exportCustomerProfitToExcel(invoices, currentAppCurrency)
  }

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="bg-gradient-to-r from-purple-600 to-pink-600 rounded-xl p-6 text-white">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold mb-2 flex items-center">
              <DollarSign className="mr-3 h-8 w-8" />
              Customer Profit Analysis
            </h1>
            <p className="text-purple-100">Analyze sales and profit generated by individual customers</p>
          </div>
          <div className="hidden md:flex items-center gap-2">
            <Button
              onClick={handleExportCustomerProfit}
              className="bg-white text-purple-600 hover:bg-purple-50 font-semibold"
            >
              <Download className="mr-2 h-4 w-4" /> Download Report
            </Button>
            <div className="bg-white/20 rounded-lg p-4">
              <BarChart3 className="h-12 w-12 text-white" />
            </div>
          </div>
        </div>
      </div>

      {/* Customer Selection */}
      <Card className="border-l-4 border-l-purple-500 hover:shadow-lg transition-shadow">
        <CardHeader>
          <CardTitle className="flex items-center text-gray-900">
            <Users className="mr-2 h-5 w-5 text-purple-600" />
            Select Customer
          </CardTitle>
          <CardDescription>Choose a customer to view their detailed profit analysis</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-4">
            <label htmlFor="customer-select" className="font-medium text-gray-700">
              Customer:
            </label>
            <Select value={selectedCustomer || ""} onValueChange={setSelectedCustomer}>
              <SelectTrigger className="w-[300px] border-purple-200 focus:border-purple-500">
                <SelectValue placeholder="Select a customer" />
              </SelectTrigger>
              <SelectContent>
                {customerNames.map((name) => (
                  <SelectItem key={name} value={name}>
                    {name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {selectedCustomer && customerProfitData ? (
        <div className="space-y-6">
          {/* Customer Stats Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="border-l-4 border-l-green-500 hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-gray-600">Total Sales</CardTitle>
                <div className="bg-green-100 p-2 rounded-full">
                  <DollarSign className="h-4 w-4 text-green-600" />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-gray-900">
                  {formatCurrency(customerProfitData.totalCustomerSales, currentAppCurrency)}
                </div>
                <p className="text-xs text-gray-500">Total revenue from {selectedCustomer}</p>
              </CardContent>
            </Card>

            <Card className="border-l-4 border-l-red-500 hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-gray-600">Total Cost</CardTitle>
                <div className="bg-red-100 p-2 rounded-full">
                  <DollarSign className="h-4 w-4 text-red-600" />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-gray-900">
                  {formatCurrency(customerProfitData.totalCustomerCost, currentAppCurrency)}
                </div>
                <p className="text-xs text-gray-500">Cost of goods sold</p>
              </CardContent>
            </Card>

            <Card className="border-l-4 border-l-purple-500 hover:shadow-lg transition-shadow">
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-gray-600">Total Profit</CardTitle>
                <div className="bg-purple-100 p-2 rounded-full">
                  <TrendingUp className="h-4 w-4 text-purple-600" />
                </div>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold text-green-600">
                  {formatCurrency(customerProfitData.totalCustomerProfit, currentAppCurrency)}
                </div>
                <p className="text-xs text-gray-500">
                  {customerProfitData.customerProfitPercentage.toFixed(2)}% Profit Margin
                </p>
                <div className="mt-2">
                  <Progress value={Math.min(customerProfitData.customerProfitPercentage, 100)} className="h-2" />
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Product-wise Profitability */}
          <Card className="border-l-4 border-l-pink-500 hover:shadow-lg transition-shadow">
            <CardHeader>
              <CardTitle className="flex items-center text-gray-900">
                <BarChart3 className="mr-2 h-5 w-5 text-pink-600" />
                Product-wise Profitability
              </CardTitle>
              <CardDescription>Breakdown of profit by individual products for {selectedCustomer}</CardDescription>
            </CardHeader>
            <CardContent>
              {customerProfitData.productSales.length > 0 ? (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-gradient-to-r from-pink-50 to-purple-50">
                        <TableHead className="font-semibold text-gray-700">Product Name</TableHead>
                        <TableHead className="font-semibold text-gray-700">Quantity Sold</TableHead>
                        <TableHead className="font-semibold text-gray-700">Total Sales</TableHead>
                        <TableHead className="font-semibold text-gray-700">Total Cost</TableHead>
                        <TableHead className="font-semibold text-gray-700">Profit/Loss</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {customerProfitData.productSales.map((item) => (
                        <TableRow key={item.productName} className="hover:bg-pink-50/50 transition-colors">
                          <TableCell className="font-medium text-gray-900">{item.productName}</TableCell>
                          <TableCell>
                            <Badge variant="secondary" className="bg-blue-100 text-blue-800">
                              {item.quantitySold}
                            </Badge>
                          </TableCell>
                          <TableCell className="font-semibold text-gray-900">
                            {formatCurrency(item.totalSales, currentAppCurrency)}
                          </TableCell>
                          <TableCell className="text-gray-600">
                            {formatCurrency(item.totalCost, currentAppCurrency)}
                          </TableCell>
                          {/* Always show profit in green */}
                          <TableCell className="text-green-600 font-semibold">
                            {formatCurrency(item.profit, currentAppCurrency)}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              ) : (
                <div className="text-center py-8">
                  <div className="bg-pink-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                    <BarChart3 className="h-8 w-8 text-pink-600" />
                  </div>
                  <p className="text-gray-500">No product sales data for this customer.</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Customer Invoices */}
          <Card className="border-l-4 border-l-blue-500 hover:shadow-lg transition-shadow">
            <CardHeader>
              <CardTitle className="flex items-center text-gray-900">
                <Eye className="mr-2 h-5 w-5 text-blue-600" />
                Invoices for {selectedCustomer}
              </CardTitle>
              <CardDescription>All invoices and transactions for this customer</CardDescription>
            </CardHeader>
            <CardContent>
              {customerProfitData.customerInvoices.length > 0 ? (
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-gradient-to-r from-blue-50 to-purple-50">
                        <TableHead className="font-semibold text-gray-700">Invoice ID</TableHead>
                        <TableHead className="font-semibold text-gray-700">Date</TableHead>
                        <TableHead className="font-semibold text-gray-700">Total Amount</TableHead>
                        <TableHead className="font-semibold text-gray-700">Profit</TableHead>
                        <TableHead className="font-semibold text-gray-700">Actions</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {customerProfitData.customerInvoices.map((invoice) => (
                        <TableRow key={invoice.id} className="hover:bg-blue-50/50 transition-colors">
                          <TableCell className="font-medium text-blue-700">{invoice.id}</TableCell>
                          <TableCell className="text-gray-600">{formatDate(invoice.createdAt)}</TableCell>
                          <TableCell className="font-semibold text-gray-900">
                            {formatCurrency(invoice.totalAmount, currentAppCurrency)}
                          </TableCell>
                          {/* Always show profit in green */}
                          <TableCell className="text-green-600 font-semibold">
                            {formatCurrency(invoice.totalProfit, currentAppCurrency)}
                          </TableCell>
                          <TableCell>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => onViewInvoice(invoice)}
                              className="border-blue-200 text-blue-600 hover:bg-blue-50"
                            >
                              <Eye className="h-4 w-4 mr-1" />
                              View
                            </Button>
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              ) : (
                <div className="text-center py-8">
                  <div className="bg-blue-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                    <Eye className="h-8 w-8 text-blue-600" />
                  </div>
                  <p className="text-gray-500">No invoices found for this customer.</p>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      ) : (
        <Card className="border-l-4 border-l-gray-300">
          <CardContent className="py-12">
            <div className="text-center">
              <div className="bg-gray-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <Users className="h-8 w-8 text-gray-400" />
              </div>
              <p className="text-gray-500 text-lg">Please select a customer to view their profit details</p>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
